name: SwiftLint

on:
  workflow_dispatch:

  pull_request:

jobs:
  lint:
    name: SwiftLint
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run:
          brew install swiftlint

      - name: SwiftLint
        run:
          swiftlint lint --reporter github-actions-logging
