name: SwiftLint

on:
  workflow_dispatch:

  pull_request:

jobs:
  lint:
    name: SwiftLint
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run:
          xcodes select 16.0

      - name: SwiftLint
        run:
          swift package plugin swiftlint --reporter github-actions-logging
