name: SwiftLint

on:
  workflow_dispatch:

  pull_request:

jobs:
  lint:
    name: SwiftLint
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: SwiftLint
        run:
          swiftlint lint --reporter github-actions-logging

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          retention-days: 7
          if-no-files-found: ignore
